# Generated by Django 5.0.14 on 2026-06-23 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Debe tener entre 7 y 15 dígitos (puede iniciar con +).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Código postal inválido. Debe tener entre 4 y 10 dígitos numéricos.', regex='^\\d{4,10}$')]),
        ),
    ]
